/* ============================================================
   JOSEPH DWYER — portfolio-next data model
   All figures sourced from the real systems:
   - PFC Supervisor (control plane + Pulse command widget)
   - v5 demo data model (project-tabs-data.js / index.html / v3.js)
   - llama-bench-portfolio run-20260814-174625 (12 native llama-bench runs, SYCL/Arc Pro B70)
   - llama-mtp-broad run-20260814-192836 model-summary.csv (MTP sweep, 27 runs)
   - qwen38-prod-bench (13 tuned MTP-draft production runs, 192k ctx)
   - llama-mtp-bench (Qwen3.6-35B per-category MTP, baseline + n2/n4/n8)
   - Resume Dwyer.pdf
   No invented numbers.
   ============================================================ */

const PORTFOLIO = (window.PORTFOLIO = {
  /* ---- Systems map nodes (architecture) ---- */
  systems: {
    core: { id: "b70", label: "B70 — PFP", sub: "Personal Fabrication Pipeline (pfp-server) · Fedora 44 · 3D-printed chassis" },
    edges: [
      { from: "b70", to: "hermes",  label: "local inference" },
      { from: "b70", to: "pfc",     label: "Wake-on-LAN · telemetry" },
      { from: "b70", to: "orch",    label: "job queue · 8090" },
      { from: "b70", to: "ts",      label: "tailnet" },
    ],
    nodes: [
      { id: "hermes", label: "Hermes / Odysseus", sub: "agent workflows · human-reviewed", kind: "agent" },
      { id: "pfc",    label: "Pi 3B+ — PFC Controller", sub: "PFC Supervisor + Pulse · Pi OS 13 · voice/command control plane", kind: "control" },
      { id: "orch",   label: "Print Orchestrator", sub: "fleet · jobs · failure detection", kind: "control" },
      { id: "ts",     label: "Tailscale — Private VPN", sub: "isolated tailnet — spreads operations securely outside the home network", kind: "net" },
      { id: "pi",     label: "Raspberry Pi", sub: "energy ledger · always-on low-power keeper", kind: "hw" },
      { id: "pfp",    label: "PFP host — B70", sub: "the Personal Fabrication Pipeline · Fedora 44 · AI runtime", kind: "hw" },
      { id: "coreone",label: "Prusa Core One — PrusaLink node", sub: "adapted PrusaLink harness routes it into the in-house fleet software", kind: "hw" },
      { id: "voron",  label: "Voron / E3NG", sub: "Klipper · CoreXY", kind: "hw" },
    ],
  },

  /* ---- Project workspaces (software) ---- */
  workspaces: [
    {
      id: "pfc",
      tag: "CONTROL PLANE",
      name: "PFC Supervisor",
      version: "control plane · Pulse command widget",
      blurb: "A self-built control plane that supervises a Pi + PFP-host pair: an AI management UI over llama.cpp and vLLM runtimes, Tailscale, the Minecraft server, and a power-management policy engine that puts idle machines to sleep — plus a desktop/mobile 'Pulse' command widget for voice and one-tap fleet control, with a savings ledger that stays honest.",
      accent: "acid",
      facts: [
        { k: "Target nodes", v: "Raspberry Pi OS 13 + Fedora 44" },
        { k: "API schema", v: "1.4.0" },
        { k: "HTTP model", v: "bounded 24-worker gate · PFC_HTTP_MAX_WORKERS" },
        { k: "Backpressure", v: "503 SERVER_BUSY · Retry-After: 1 when saturated" },
        { k: "GET dedupe", v: "single-flight protection · 45s browser timeout" },
        { k: "HDMI state", v: "WAITING · ONLINE · STALE · FAULT (5 fails + 30s)" },
        { k: "Concurrency", v: "listen backlog 64→128 · 24-worker ceiling" },
        { k: "Theming", v: "light · dark · system · animated interface framework" },
        { k: "AI mgmt UI", v: "llama.cpp + vLLM runtime lifecycle per model" },
      ],
      scope: [
        "control-plane foundation + multi-page operations console",
        "Pi telemetry & maintenance framework",
        "PFP host telemetry + Hermes scheduled Wake-on-LAN",
        "authenticated PFP service operations",
        "llama.cpp + vLLM runtime management (start/stop/status per model)",
        "Minecraft player/command management + transactional provisioning",
        "power-management console + policy engine",
        "Pi-retained energy ledger & net energy-savings attribution",
        "daily auto-on / auto-off timeline",
      ],
      power: [
        { v: "AI RUNTIME", l: "llama.cpp + vLLM manager", s: "concurrent model runtimes · start/stop/status per model" },
        { v: "TAILSCALE",  l: "private VPN tailnet", s: "secure operations outside the home network" },
        { v: "MINECRAFT",  l: "managed server service", s: "transactional player/command provisioning" },
        { v: "95.0 h",     l: "observed sleep", s: "power-management policy · 13.19 kWh avoided / 7-day" },
      ],
      shots: [
        { id: "pfc-power-management", cap: "Power-management console — policy engine, daily auto-on/off timeline" },
        { id: "pfc-runtime",          cap: "Concurrent AI runtime management view" },
        { id: "pfc-runtime-grid",     cap: "Runtime grid — all model runtimes at a glance" },
        { id: "pfc-telemetry",        cap: "Node telemetry — Pi + PFP host vitals" },
        { id: "pfc-pulse-command",    cap: "Pulse — voice + one-tap fleet control from the desktop/phone" },
        { id: "pfc-control-plane",    cap: "Control-plane overview" },
        { id: "pfp-host",             cap: "PFP host view from the supervisor" },
      ],
      shotNote: "Live console screens from the running supervisor — power management, runtime grid, telemetry, and the PFP host view.",
      docs: [
        { h: "What it is", p: "PFC Supervisor is a self-hosted control plane written from scratch: one supervisor process supervising two managed nodes (a Raspberry Pi running OS 13 as the always-on low-power keeper, and the Fedora 44 PFP host that carries the heavy AI workload). Everything the user would normally click through vendor UIs for — service state, telemetry, power policy, AI runtime lifecycle — is one local HTTP API with a versioned schema (1.4.0) and a console on top." },
        { h: "The HTTP model", p: "The supervisor exposes a bounded 24-worker gate (PFC_HTTP_MAX_WORKERS) with a listen backlog tuned from 64 to 128. When the gate saturates it answers 503 SERVER_BUSY with Retry-After: 1 instead of queuing unboundedly — backpressure as a first-class contract. GET endpoints are single-flight deduped: N concurrent identical reads execute one fetch, and a 45-second browser timeout cap keeps wedged clients from holding a worker." },
        { h: "State, honestly", p: "Node HDMI/display state runs an explicit state machine: WAITING → ONLINE → STALE → FAULT, where FAULT is 5 consecutive misses plus a 30-second grace window. The supervisor does not pretend a node is healthy because it is reachable — liveness and display readiness are tracked separately, and the console shows the transition history." },
        { h: "Power policy engine", p: "The power-management console and policy engine run a daily auto-on/auto-off timeline, an idle-to-sleep policy, and a Pi-retained energy ledger that attributes net savings (PFP kWh avoided minus Pi overhead) so the ledger is honest rather than a gross figure. Observed result: 154.8 W combined active load (PFP 150.0 W est. + Pi 4.8 W est.), 95.0 h of observed sleep, 13.19 kWh avoided over 7 days ($4.62 net avoided at PFP 13.77 kWh), and a 68.23 kWh 30-day projection under the same policy." },
        { h: "AI runtime + sidecars", p: "The control plane's primary job is the AI management UI: llama.cpp and vLLM runtimes are managed as first-class services — start/stop/status per model, worker endpoints, and vision projector handling — so swapping or stacking local models is a console operation, not a terminal session. As a real-world workload it also runs a Minecraft server with transactional player/command provisioning over the same Tailscale tailnet — the supervisor treats game ops as just another authenticated service surface." },
        { h: "Pulse — the command widget", p: "Pulse is the human face of the supervisor: a lightweight Plasma 6 command widget (desktop or phone) that mirrors the control plane and gives one-tap, authenticated reach to the fleet. It shows live status chips (local ready, Hermes health, tunnel state), a 'hold to talk' voice path and an 'Ask Hermes' box for typed instructions, and can read the latest supervisor response aloud. Without credentials it still shows the public health summary — wake, suspend, and schedule stay locked behind authentication, so the widget is a control surface, not a back door. It is the same supervisor API the full console uses, just shaped for a thumb at the desk or on the move." },
      ],
    },
    {
      id: "orch",
      tag: "FLEET OPS",
      name: "Print Orchestrator",
      version: "dashboard · 8090",
      blurb: "A local fleet dashboard over mixed printers (PrusaLink + Moonraker) with unified jobs, server health, per-printer power, and camera-based part-presence failure detection — plus an AI-powered auto-CAD and auto-slicing service that takes a design intent all the way to a queued, watched print. Human monitoring gateways sit at the key decision points; with them cleared, the pipeline runs fully independent of human operation.",
      accent: "cyan",
      facts: [
        { k: "Transports", v: "PrusaLink (Core One) + Moonraker (Voron/Klipper)" },
        { k: "Pages", v: "Fleet · Jobs · Server · Power · Failure Detection · PrusaLink" },
        { k: "Failure detect", v: "camera part-presence scoring" },
        { k: "Part gate", v: "clear ≤ 0.030 · part ≥ 0.065" },
        { k: "Confirmation", v: "17/3 confirmations on primary camera" },
        { k: "Power", v: "per-outlet live · safe power off" },
        { k: "Host", v: "pfp-server · Tailscale reachable" },
        { k: "Auto-CAD → slice", v: "AI design-intent to queued G-code" },
        { k: "Autonomy", v: "human gateways at decision points · unattended once cleared" },
      ],
      scope: [
        "multi-printer fleet with mixed PrusaLink / Moonraker backends",
        "unified job queue + progress + remaining-time estimation",
        "server health + worker accounting",
        "per-printer power with safe power-off",
        "camera part-presence failure detection with scoring thresholds",
        "AI auto-CAD + auto-slicing from design intent to queued G-code",
        "human monitoring gateways at decision points · fully independent operation once cleared",
        "Tailscale-exposed local dashboard (8090)",
      ],
      shots: [
        { id: "po-fleet",              cap: "Fleet view — mixed PrusaLink + Moonraker printers, one dashboard" },
        { id: "po-jobs",               cap: "Jobs — unified queue with progress + remaining-time estimates" },
        { id: "po-server",             cap: "Server health + worker accounting" },
        { id: "po-power",              cap: "Per-outlet live power with safe power-off" },
        { id: "po-failure-detection",  cap: "Failure detection — camera part-presence scoring" },
        { id: "po-prusalink",          cap: "PrusaLink backend detail (Core One)" },
        { id: "pfp-chassis-print",     cap: "The PFP chassis itself, printing on the Core One" },
        { id: "coreone-printing",      cap: "Core One mid-print, watched by the orchestrator" },
      ],
      shotNote: "Fleet, jobs, server, power, and failure-detection views from the running dashboard, plus the PFP chassis print on the Core One.",
      docs: [
        { h: "Why two transports", p: "The fleet is genuinely mixed: a Prusa Core One speaks PrusaLink; the Voron/Klipper machines speak Moonraker. The orchestrator normalizes both into one fleet model — same job schema, same health schema, same power schema — so the dashboard never cares which firmware is behind a node. Adding a printer is a backend choice, not a UI rewrite." },
        { h: "Failure detection that doesn't cry wolf", p: "Part-presence detection runs off the primary camera and scores each frame into two gates: a bed is CLEAR at score ≤ 0.030 and a part is PRESENT at score ≥ 0.065; the band in between is treated as indeterminate rather than guessed. The primary camera banked 17/3 confirmations (17 part-present, 3 clear) before the threshold shipped — the decision is made from measured score distributions, not from a hunch." },
        { h: "Power as a control surface", p: "Per-outlet live wattage is treated as a first-class page: you can see each printer's plug draw, and the safe-power-off path goes through the supervisor's authenticated service operations rather than a hard cut — the machine parks first, then power drops." },
        { h: "From model to print — AI auto-CAD + auto-slicing", p: "The pipeline that feeds the fleet starts from design intent, not from hand-drawn geometry. An AI auto-CAD stage turns the intent into parametric geometry — scripted, dimensional, regenerable — and an auto-slicing stage turns that into G-code with the per-printer profile (material, nozzle, heightmap compensation, tuned Klipper/pressure-advance settings) applied. Human monitoring gateways sit at the key decision points: design intent accepted, generated model approved, sliced job released. Once those gateways are cleared, the run is fully independent of human operation — the job is queued, its temperatures and progress are watched, and the part-presence camera scores it while it prints, with no human in the loop." },
        { h: "Deployment", p: "Runs as a systemd user service (python3 -m src.server, port 8090) on pfp-server, reachable over the tailnet. It is the operational front door for the whole print fleet — the interactive replica in the Live Systems section is built 1:1 from this running dashboard." },
      ],
    },
    {
      id: "hermes",
      tag: "AGENT LAYER",
      name: "Hermes / Odysseus",
      version: "local-first agent workflows",
      blurb: "A human-in-the-loop agent layer on the B70: email triage, human-reviewed draft generation, translation, meeting minutes, calendar support, research summaries, and supervised digital-manufacturing workflows — all local, all private.",
      accent: "violet",
      facts: [
        { k: "Runtime", v: "Hermes Agent · local models (Qwen/Gemma)" },
        { k: "Model", v: "Qwen 3.8-27B · GPTQ-INT4 G128 + MTP4 (vLLM XPU)" },
        { k: "Network", v: "local worker endpoint (/v1 on :11436) · Tailscale" },
        { k: "Review model", v: "human-reviewed drafts · no silent auto-send" },
        { k: "Workflows", v: "email triage · minutes · translation · research" },
        { k: "Print", v: "slicer prep · job scheduling · status monitoring" },
      ],
      scope: [
        "email triage + human-reviewed draft generation",
        "translation + meeting-minute generation",
        "calendar support + technical research summaries",
        "task review + documentation assistance",
        "supervised slicer prep, printer job scheduling, status monitoring",
        "local-first: engineering context stays on the tailnet",
      ],
      shots: [],
      shotNote: "",
      noPhotos: true,
      whatIs: [
        { h: "What Hermes is", p: "Hermes Agent (by Nous Research) is a local-first AI agent framework: a gateway that connects channels (Discord, CLI, web) to a model runtime, with tools for terminal, files, browser, memory, scheduled jobs, and skills. On the B70 it runs against a local vLLM XPU worker endpoint (/v1 on :11436) serving Qwen 3.8-27B (GPTQ-INT4 G128 + MTP4, with the tool-call and reasoning parsers it needs) — so the agent's entire context, drafts, and tool calls never leave the tailnet." },
        { h: "Why it matters here", p: "This portfolio was built by the system it describes. Hermes (running on the B70, over Discord) inventories the packet of project assets, extracts the real benchmark figures, curates the photos, and patches this site — while a human reviews every step. It is the 'agent layer' node in the systems map, and it is the most-used workflow I run." },
      ],
      howIUse: [
        "Email triage and human-reviewed draft replies — the agent drafts, I approve; nothing auto-sends.",
        "Meeting minutes + translation + research summaries from local documents.",
        "Supervised digital manufacturing: slicer prep, printer job scheduling, status monitoring through the orchestrator/PFC APIs.",
        "Scheduled jobs (cron) for briefings and watchdogs — memory/disk/power alerts with no tokens burned when there's nothing to say.",
        "Self-documentation: the agent maintains its own skills and memory, so recurring procedures (printer ops, benchmark parsing, deploy steps) get better every session.",
      ],
      links: [
        { label: "Hermes Agent — Nous Research (GitHub)", url: "https://github.com/NousResearch/hermes-agent" },
        { label: "Hermes Agent documentation", url: "https://hermes-agent.nousresearch.com/docs" },
      ],
    },
  ],

  /* ---- Mechanical / hardware projects ---- */
  projects: [
    {
      id: "b70", name: "B70 AI Automation Server", cat: "SELF-HOSTED INFRA · HERO", accent: "acid",
      role: "Designed, built & run the whole stack",
      blurb: "The flagship: a self-hosted AI automation server on enterprise hardware (Intel Arc Pro B70, Ryzen 7 5700X) in a custom 3D-printed orange chassis — Fedora 44, vLLM XPU + llama.cpp, Qwen/Gemma models, Tailscale, and the Hermes agent layer. 100% local, 100% private.",
      facts: ["Intel Arc Pro B70 (Battlemage G31) · SYCL", "Ryzen 7 5700X · B550M Pro SE", "custom 3D-printed chassis", "Fedora 44 · vLLM XPU 0.27.2 + llama.cpp", "Qwen3.8-27B primary + Gemma family", "Tailscale tailnet · Hermes agents"],
      shots: [
        { id: "pfp-host-physical", cap: "The B70 in its 3D-printed orange chassis — the server behind every system on this page" },
        { id: "pfp-host-open",     cap: "Interior: Arc Pro B70, Ryzen 7 5700X, and the PSU in the printed case" },
        { id: "pfp-host-room",     cap: "Front view — status display and the printed front panel" },
        { id: "pfp-host-top",      cap: "Top-down: the honeycomb-printed top plate and venting" },
      ],
      featured: true,
      docs: [
        { h: "The machine", p: "The B70 is a self-hosted AI automation server on enterprise hardware: Intel Arc Pro B70 (Battlemage G31) under an IntelLLVM 2026.1.1 / SYCL toolchain, an AMD Ryzen 7 5700X, on a B550M Pro SE board. It runs Fedora 44 and serves the entire local stack — vLLM XPU inference for the primary model (plus a llama.cpp endpoint for the rest of the model library), the Hermes agent layer, the Print Orchestrator, and the Hermes dashboard — all on one host, all private." },
        { h: "The chassis", p: "The enclosure is custom: a 3D-printed orange case (honeycomb top plate, integrated display window, vented front) printed on the Core One that the same server orchestrates. The server that prints its own housing and then watches it print is the point — the whole loop is local." },
        { h: "The runtime", p: "The primary model — Qwen 3.8-27B — is now served by vLLM XPU (0.27.2rc1, pinned openai-xpu image) in a Podman container on port 11436: GPTQ-INT4 (symmetric, G128) weights with the MTP draft head preserved in BF16, MTP4 speculative decoding, 160k context, FP8 KV cache, XPU graph engine. It runs 84.65 tok/s short-context decode versus 19.92 t/s for llama.cpp (and still ~51.5 t/s at 80K cold context) — the benchmark section below opens with this configuration and its reference recipe, then shows the llama.cpp history (llama-bench + MTP sweeps) that the switch replaced. llama.cpp 10369 (SYCL, ngl 99) stays on the machine for the rest of the model library." },
        { h: "Network", p: "Tailscale (tailnet 'yonchers.github') connects pfp-server to the fedora client and remote devices. Firewalled by default; individual ports (9119 dashboard, 8090 orchestrator, 8098 portfolio) get explicit firewall-cmd rules. The portfolio you're reading is served by a systemd user service (port 8098) that survives reboots via linger." },
      ],
      links: [
        { label: "B70 Qwen3.8-27B vLLM XPU (main reference)", url: "https://github.com/MikeCaldera/intel-arc-pro-b70-qwen38-vllm" },
        { label: "llama.cpp", url: "https://github.com/ggml-org/llama.cpp" },
        { label: "Tailscale", url: "https://tailscale.com" },
        { label: "Hermes Agent — Nous Research", url: "https://github.com/NousResearch/hermes-agent" },
      ],
    },
    {
      id: "e3ng", name: "E3NG Custom CoreXY", cat: "3D PRINT · KLIPPER", accent: "acid",
      role: "Designed, printed & tuned the build",
      blurb: "An RH3D E3NG build — an Ender 3 recycled into a CoreXY: reuses the original Ender 3's parts, then rebuilds it as a fast, enclosed, Klipper-driven CoreXY with a continuous eddy-current bed sensor, tuned and printed for engineering-grade parts.",
      facts: ["Ender 3 → CoreXY (RH3D E3NG)", "reuses the original Ender 3's parts", "Klipper · enclosed build", "eddy-current bed sensor (continuous)"],
      shots: [
        { id: "e3ng-hero",     cap: "The E3NG — full build" },
        { id: "e3ng-toolhead", cap: "Toolhead assembly" },
        { id: "e3ng-klipper",  cap: "Bed-probe graph — the continuous heightmap" },
        { id: "e3ng-psu",      cap: "Eddy-current bed sensor" },
        { id: "e3ng-cam",      cap: "Camera + part-presence view" },
        { id: "e3ng-bench",    cap: "Completed build" },
        { id: "e3ng-cad",      cap: "CAD of custom parts" },
        { id: "e3ng-top",      cap: "Finalizing the gantry wiring" },
        { id: "e3ng-works",    cap: "Wireless print monitoring" },
      ],
      docs: [
        { h: "The Ender 3 origin", p: "The E3NG (Ender 3 Next Generation, by RH3D) is a conversion, not a new machine: it takes an old, often-obsolete Ender 3 and recycles the bulk of its parts — frame hardware, leadscrews, the original electronics where it works — then rebuilds it as a CoreXY with linear rails, an enclosed electronics bay, and a far more rigid bed carriage. The design goal is reuse first: up to ~78% of the original printer's parts are carried over and given a second life, which is the whole point of 'NG' — an Ender 3 that is genuinely better, built from what you already owned." },
        { h: "The continuous bed sensor", p: "The bed measurement is the interesting part. Instead of a discrete click-probe that taps the bed at grid points, this build uses an eddy-current (eddy induction) sensor that measures bed height continuously as the carriage moves, producing a smooth, unbroken heightmap rather than a sampled grid. That continuous trace feeds Klipper's bed-mesh compensation, so the first layer stays glued corner to corner — the smooth graph in the gallery is that live measurement, not a static screenshot of a menu." },
        { h: "Firmware + tuning", p: "Klipper throughout. The machine was tuned through pressure-advance, input shaping, and belt tensioning iterations until the printed parts (and the printed chassis for the B70) came off clean at speed. Klipper's config is versioned and the tuned profile is part of the deliverable, not a throwaway." },
        { h: "Role in the stack", p: "The E3NG is one node in the Print Orchestrator fleet (Moonraker backend) — its jobs, temperatures, and failure-detection camera all show up in the 8090 dashboard alongside the Core One." },
      ],
      links: [
        { label: "E3NG — RH3D design (site + build docs)", url: "https://rh3d.xyz/e3ng" },
        { label: "E3NG v1.2 files — Printables", url: "https://www.printables.com/en/model/922401" },
        { label: "Klipper firmware", url: "https://github.com/Klipper3d/klipper" },
      ],
    },
    {
      id: "voron", name: "Voron 2.4", cat: "3D PRINT · KLIPPER", accent: "cyan",
      role: "Built, troubleshot & dialed in",
      blurb: "Built and troubleshot a Voron 2.4 CoreXY from frame to first layer — stepper motion, toolhead and hotend integration, custom print profiles, and full-system diagnosis until the parts came off clean at speed.",
      facts: ["Voron 2.4 CoreXY", "Klipper · high-speed profiles", "toolhead + hotend integration", "custom profiles · diagnosis"],
      shots: [
        { id: "voron-hero",      cap: "Voron 2.4 — hero shot" },
        { id: "voron-frame",     cap: "Frame assembly" },
        { id: "voron-electronics", cap: "Electronics bay — wiring, fans & drivers" },
        { id: "voron-printing",  cap: "Mid-print on the Voron" },
        { id: "voron-enclosed",  cap: "The finished, enclosed build" },
        { id: "voron-assembly",  cap: "During assembly" },
      ],
      docs: [
        { h: "The build", p: "A from-scratch Voron 2.4 CoreXY: frame assembly, the internal electronics bay (PSU, drivers, fans, and the wiring that keeps the toolhead and bed in sync), stepper motion setup, and the toolhead and hotend integration. Klipper drives it with high-speed, input-shaped profiles, and every material gets its own tuned print profile." },
        { h: "The work", p: "This is the build-and-fix layer: when something stops being straight, the loop is measure (calibration prints, the camera), tune (the Klipper profile), and verify — repeated until the part is right. Full-system diagnosis across frame, motion, and toolhead is the real skill, not just assembling a kit." },
      ],
      links: [
        { label: "Voron 2.4 design — Voron Design", url: "https://github.com/VoronDesign/Voron-2" },
        { label: "Klipper firmware", url: "https://github.com/Klipper3d/klipper" },
      ],
    },
    {
      id: "capstone", name: "ME Senior Capstone — Espresso Machine", cat: "MECHANICAL DESIGN · TEAM", accent: "violet",
      role: "Team 1 · CAD, fab & assembly",
      blurb: "ME190 senior capstone (Team 1 · Crema Crew): a hand-actuated espresso machine — CAD, worm-gear + linkage tamping mechanism, machined and 3D-printed parts, full assembly, and a final report + engineering poster.",
      facts: ["ME190 · team capstone", "hand-actuated espresso machine", "CAD → fabrication → assembly", "final report + ME190 poster"],
      shots: [
        { id: "senior-press",   cap: "Hand-actuated press + worm-gear tamping mechanism" },
        { id: "senior-gripper", cap: "Brew chamber + linkage subassembly" },
        { id: "senior-parts",   cap: "Machined and fabricated parts" },
        { id: "senior-print",   cap: "3D-printed prototype parts (Prusa Core)" },
        { id: "senior-team",    cap: "Team 1 (Crema Crew) at the build" },
        { id: "senior-report",  cap: "Final report — Hybrid Hand-Actuated Espresso Machine" },
      ],
      docs: [
        { h: "The machine", p: "The ME190 senior capstone is a hybrid hand-actuated espresso machine: a worm gear drives a linkage to give ~120:1 mechanical advantage, so a ~5 lb force on a hand lever produces the ~500 lb / 9 bar needed to pull a consistent double shot through a 58 mm portafilter. Water is heated in a coiled copper resistive element and a Raspberry Pi manages control and operation. Target: a repeatable double shot in 25–30 s at ±10% volume variance." },
        { h: "Scope", p: "A full five-member team design cycle: requirement capture, CAD (SolidWorks/Fusion), part fabrication (machining + 3D printing for prototypes), assembly, and functional testing — closed with a final report and a formal ME190 engineering poster. All deliverables are linked in the documentation tab." },
        { h: "What it shows", p: "The cleanest example of the mechanical half of this portfolio: a mechanism that actually works (pulls espresso), designed to be built, built, tested, and documented to an auditable standard — with FEA on clamp deflection, an electrical schematic, and an exploded/isometric drawing package." },
      ],
      docsDeliverables: [
        { title: "Final report — Hybrid Hand-Actuated Espresso Machine (PDF)", href: "downloads/capstone/Group1_ME190_FinalReport_WithBOM.pdf" },
        { title: "ME190 engineering poster (PDF)", href: "downloads/capstone/Group_1_Espresso_Machine_ME190_Poster.pdf", img: "assets/images/senior-poster.jpg" },
        { title: "Espresso drawing package (PDF)", href: "downloads/capstone/EspressoDrawingPackage-Group1Apr29.pdf" },
        { title: "Brew assembly — exploded view (PDF)", href: "downloads/capstone/BrewAssemblyExploded.pdf" },
        { title: "Full assembly — isometric (PDF)", href: "downloads/capstone/FullAssemblyIso.pdf" },
        { title: "Electrical schematic", href: "downloads/capstone/ElectricalSchematic.docx" },
      ],
      links: [],
    },
    {
      id: "me165", name: "ME165 · ABB / Rexroth", cat: "ROBOTICS · CONTROLS", accent: "violet",
      role: "Lab operation, motion & troubleshooting",
      blurb: "Hands-on academic robotics: ABB robot systems + Rexroth controller platforms — motion concepts, controller interaction, lab setup, troubleshooting, and automation documentation.",
      facts: ["ABB robot cells", "Rexroth controllers", "lab setup + troubleshooting", "workcell documentation"],
      shots: [
        { id: "me165-robot",  cap: "ABB robot cell" },
        { id: "me165-robot2", cap: "Robot + fixture detail" },
        { id: "me165-plc",    cap: "Rexroth controller platform" },
      ],
      docs: [
        { h: "Scope", p: "ME165 is the academic robotics core: ABB industrial robot cells and Rexroth controller platforms. The work is the full operator's loop — lab setup, controller interaction, motion programming, fault isolation and troubleshooting — plus the automation documentation that makes a workcell reproducible by the next team." },
        { h: "Why it's here", p: "This is the direct foundation for the controls & automation line on the skills page: reading a live controller, understanding motion, isolating a fault on a running cell, and writing the documentation so the workcell reproduces. It is the same loop as commissioning and supporting industrial machines in the field — the lab version, before the floor." },
      ],
      links: [],
    },
    {
      id: "metuned", name: "Metuned LLC", cat: "RACECAR ELECTRONICS · CDO", accent: "acid",
      role: "Chief Design Officer · 2023–2026",
      blurb: "Co-founded a racecar data-acquisition startup (Chief Design Officer, 2023–2026): affordable performance telemetry, prototype iteration, low-cost manufacturability, and product documentation.",
      facts: ["Chief Design Officer", "data-acquisition / telemetry", "prototype iteration", "low-cost manufacturing"],
      shots: [
        { id: "metuned-cage",       cap: "Cage-mount install" },
        { id: "metuned-cage2",      cap: "Cage install, second angle" },
        { id: "metuned-cage3",      cap: "Cage install detail" },
        { id: "metuned-dash2",      cap: "Dashboard telemetry view" },
        { id: "metuned-dash4",      cap: "Dashboard, live data" },
        { id: "metuned-box-bench",  cap: "The DAQ box on the bench" },
        { id: "metuned-exploded",   cap: "Exploded view of the DAQ enclosure" },
        { id: "metuned-screen",     cap: "On-screen acquisition" },
        { id: "metuned-brand",      cap: "Brand mark" },
      ],
      docs: [
        { h: "The product", p: "Metuned made affordable performance data acquisition for racecars: a compact DAQ box that captures telemetry from a race vehicle's harness, a dashboard for live and post-run review, and cage-mount hardware that survives a real race environment. As CDO I owned the mechanical/electrical design direction, the enclosure (exploded view shows the printed/enclosed box), and the product documentation." },
        { h: "The constraint set", p: "The interesting engineering is cost: every part choice is made against 'can a customer afford this?' — low-cost manufacturability is a design requirement, not a later optimization. Prototype iteration is fast because the parts print and machine locally." },
        { h: "The direction", p: "The product's identity was that everything stays highly customizable but ready to use out of the box — assembled, not a kit. Components were deliberately non-Chinese-sourced for reliability, and the enclosures and accessories were 3D-printed domestically so hardware could iterate without a supply-chain round-trip." },
        { h: "What happened to the company", p: "Metuned got real traction early — we were doing good off an angel investment from the Growth Factory in Rocklin, and we had the benefit of their advisors' guidance. In the end the company fell apart: R&D costs kept climbing, and we could not conclude the second revamp of the prototype in a timely way because school took priority. It stayed a strong lesson in what a startup actually costs to move from a working prototype to a sellable product — and the data-acquisition design work above is what came out of it." },
      ],
      links: [],
    },
    {
      id: "motorsports", name: "Motorsports Club · 24h Lemons", cat: "TEAM LEADERSHIP · BUILD", accent: "cyan",
      role: "Club officer · led the build",
      blurb: "President/VP/Treasurer of the Sierra College Motorsports Club — led a 24 Hours of Lemons Mini Cooper build: race prep, sponsorship/outreach, funding (including a 3D-printed keychain fundraiser), welding, and real-time race support.",
      facts: ["24 Hours of Lemons", "Mini Cooper build", "sponsorship + funding", "Cars & Coffee keychain fundraiser", "real-time race support"],
      shots: [
        { id: "car-track",        cap: "On track" },
        { id: "car-welding",      cap: "Welding the roll cage" },
        { id: "car-caliper",      cap: "Measuring tube stock" },
        { id: "car-chassis-print",cap: "Club go-kart — club days recruitment" },
        { id: "car-cockpit",      cap: "VR sim rig — bucket seat & harness" },
        { id: "car-dash",         cap: "Student project — exo-set Miata dash (gauges, switch panel & cage)" },
        { id: "car-cab",          cap: "Snapped control-arm repair" },
        { id: "car-wheel-detail", cap: "Fabricating the transmission mount" },
        { id: "car-parts-crate",  cap: "Keychains I designed — the box from the Cars & Coffee run" },
        { id: "car-3dprint",      cap: "Printing the keychains — CR-10 Max V3 run for the club fundraiser" },
        { id: "car-tent",         cap: "The #115 in full livery at the team tent" },
        { id: "car-pitlane",      cap: "Pit lane — watching the field" },
        { id: "car-engine",       cap: "Replacement pick-and-pull motor" },
        { id: "car-team",         cap: "The team at the car" },
        { id: "car-paddock",      cap: "Full crew at Sonoma" },
        { id: "car-team-pit",     cap: "Pit support" },
        { id: "car-night-team",   cap: "Night session — 24-hour race conditions" },
        { id: "car-award",        cap: "Finish-line award" },
        { id: "hoonigan-race",    cap: "At a Hoonigan event" },
      ],
      docs: [
        { h: "The role", p: "As President/VP/Treasurer of the Sierra College Motorsports Club I ran both sides of a 24 Hours of Lemons Mini Cooper build: the engineering side (race prep, roll-cage welding, engine bay, real-time race support through a 24-hour event) and the organizational side (sponsorship/outreach, event funding, team coordination)." },
        { h: "Cars & Coffee — the keychain fundraiser", p: "One of the funding channels the club ran was 3D-printed car keychains for donation at Cars & Coffee events: I designed the pendant and ran the print jobs (the CR-10 Max V3 in the gallery handled the runs), then sold them at the events. Small object, full loop — design, print, finish, sell, and put money back into the build." },
        { h: "Sonoma", p: "The club's first managed race at Sonoma Raceway was the first full test of the whole loop: a car, a budget, a schedule, and a crew that had to perform under real track time. The wrap-up deck documents the event — the car, the results, the lessons, and what it proved about running a team through a hard deadline." },
        { h: "Why it's here", p: "It is the leadership proof: leading a team through a hard deadline with a budget, a car, and a track. The same skills — schedule, money, people, and a machine that has to actually work — are what equipment and production engineering jobs run on." },
      ],
      docsDeliverables: [
        { title: "Sonoma Raceway — First Race Wrap-Up (PDF, 17 pp)", href: "downloads/motorsports/Sonoma_Wrap_Up.pdf", img: "assets/images/car-sonoma-cover.jpg" },
        { title: "Sonoma Raceway — Pit-lane timelapse (video, 57s)", href: "assets/video/sonoma-timelapse.mp4", img: "assets/video/sonoma-timelapse-poster.jpg" },
      ],
      links: [
        { label: "Sierra College Motorsports (Instagram)", url: "https://www.instagram.com/sierracollegemotorsports/" },
        { label: "Sierra College — Sonoma Raceway Mini Cooper (news)", url: "https://www.sierracollege.edu/about-sierra-college/news/car-club-sonoma-raceway-mini-cooper/" },
        { label: "On track — YouTube", url: "https://www.youtube.com/watch?v=Ou3vfj8c498" },
      ],
    },
    {
      id: "uei", name: "UEI Lab · Energy Testing", cat: "TEST & MEASUREMENT", accent: "violet",
      role: "Lab assistant · measurement & docs",
      blurb: "Lab assistant supporting CEC appliance energy-efficiency audits, portable-spa testing, and residential fan airflow/CFM testing aligned to HVI 916 — controlled environments, repeatability, documentation.",
      facts: ["CEC energy audits", "HVI 916 fan/CFM", "test-environment build", "data + documentation"],
      shots: [
        { id: "uei-rig",       cap: "Test rig" },
        { id: "uei-fan",       cap: "Fan under test" },
        { id: "uei-blower",    cap: "Blower test" },
        { id: "uei-tunnel",    cap: "Airflow tunnel" },
        { id: "uei-squarefan", cap: "Square-fan CFM test" },
        { id: "uei-logger",    cap: "Data logger" },
        { id: "uei-room",      cap: "Controlled test room" },
      ],
      docs: [
        { h: "The work", p: "At University Enterprises Inc. (Sacramento State) I support CEC appliance energy-efficiency audits, portable-spa testing, and residential fan airflow/CFM testing aligned to HVI 916. The through-skill is measurement discipline: controlled test environments, calibrated instrumentation, repeatability runs, and documentation good enough for a regulatory audit." },
        { h: "Connection to the PFC", p: "This lab work is the mechanical origin of the PFC power policy engine: measuring real appliance draw, understanding what 'avoided energy' actually means, and keeping a ledger honest. The 13.19 kWh / 7-day figure in the PFC section is that discipline applied to the home fleet." },
      ],
      links: [],
    },
  ],

  /* ---- In progress (things in progress, documentation soon) ---- */
  inprogress: [
    {
      id: "e3ng-48v", name: "E3NG Continuation", cat: "3D PRINT · 48V REBUILD", accent: "acid", status: "IN BUILD",
      blurb: "Swapping the E3NG's motors over to 48V power and upgrading the electronics to make proper use of the 5160 steppers — plus more fans and better electronics cooling, durability improvements, and a refreshed toolhead using higher-quality prints to reduce vibration from tolerance discrepancies.",
      facts: ["48V power swap", "5160 steppers", "more fans · cooled electronics", "durability pass", "re-optimized toolhead"],
      art: "e3ng-48v",
    },
    {
      id: "sae", name: "SAE Motorsports", cat: "MOTORSPORTS · OUTREACH", accent: "cyan", status: "SEEKING TEAM",
      blurb: "Looking to join an SAE club on campus to contribute in manufacturing, electronics, or systems — getting hands-on racecar experience before graduation.",
      facts: ["on-campus SAE club", "manufacturing · electronics · systems"],
      art: "sae-motorsports",
    },
    {
      id: "robotics-bin", name: "Robotics Integration", cat: "AUTOMATION · LOCAL LLM", accent: "cyan", status: "CONCEPT",
      blurb: "Looking to add robotic automation and controls to my manufacturing workflow — a conception of a CAD-to-stock-holding-bin pipeline with minimal human supervision, as a testament to local LLM capability in the open-source community.",
      facts: ["CAD → stock bin", "minimal supervision", "local LLM showcase", "open source"],
      art: "robotics-integration",
    },
    {
      id: "me191", name: "Senior Project Finish Line", cat: "ACADEMIC · ME191", accent: "violet", status: "DUE DEC 2026",
      blurb: "Finalizing the ME190 work in ME191 and carrying it to a complete, presentation-ready state — done by December 2026.",
      facts: ["ME190 → ME191", "presentation complete Dec 2026"],
      art: "senior-project",
    },
    {
      id: "korean", name: "Korean, Built Locally", cat: "LANGUAGE · LOCAL APP", accent: "violet", status: "ACTIVE",
      blurb: "Learning Korean with a locally built language app off Hermes, supported by Korean 1A at Sac State — with the goal of eventually passing TOPIK at level 4 or greater.",
      facts: ["built locally on Hermes", "Korean 1A @ Sac State", "goal: TOPIK ≥ 4"],
      art: "korean-learning",
    },
  ],

  /* ---- Benchmarks (real run data) ---- */
  benchmarks: {
    shortVersion: {
      title: "The short version",
      points: [
        "The B70 runs my main AI model (Qwen 3.8-27B) fully on this machine — nothing is sent to any cloud, and it answers at 84.65 tokens/sec. That is about 4x faster than the previous local setup (19.92 t/s).",
        "Speed holds up on long conversations: at a 120,000-token context it still generates at ~50 t/s (a ~40% drop, not a collapse) — long sessions stay usable instead of stalling.",
        "The box also runs 11 other local models, from a 0.8B background assistant (202 t/s) to 27–35B workhorses (20–77 t/s). Every number below was measured on this hardware, not quoted from a vendor — including the ones that came out badly.",
      ],
    },
    vllm: {
      title: "The main model — what it does now",
      run: "reference recipe · medians (n=5) · 230 W GPU cap",
      sub: "Qwen 3.8-27B, served locally by vLLM XPU on the Arc Pro B70. Recipe base: MikeCaldera/intel-arc-pro-b70-qwen38-vllm, run here with internal tweaks (Podman, prefix caching off, 2048-token batch, tool-call/reasoning parsers for the agent layer).",
      cols: ["workload", "context", "gen t/s", "plain-english result"],
      rows: [
        ["Typical short exchange", "512 prompt / 128 gen", 84.65, "median 84.49 · range 83.73–84.78 (n=5) · first-token 0.36 s"],
        ["Long session, cold start", "80,000 prompt / 128 gen", 51.5, "6/6 passes · ~96.6% draft acceptance · first token ~81.5 s (one-time prefill)"],
        ["Context scaling", "512 → 120k", null, "81.2 → 73.3 → 74.8 → 68.3 → 66.1 → 50.3 t/s across 512/8k/16k/32k/65k/120k — degrades gradually, never collapses"],
      ],
      kv: [
        { k: "what runs", v: "Qwen 3.8-27B, 4-bit (GPTQ) weights, BF16 draft head — 5 × ~4 GB shards" },
        { k: "drafting", v: "MTP4: the model drafts 4 tokens at a time; high acceptance (92–98% on the Pi prompt set) is what makes it fast" },
        { k: "context", v: "160k max — verified by 3 consecutive full 160k passes (~245 s each) with FP8 KV cache" },
        { k: "where it lives", v: "local /v1 on port 11436 — the entire agent stack talks to it privately over Tailscale" },
      ],
      findings: [
        "84.65 t/s on short exchanges vs 19.92 t/s for the previous llama.cpp setup — ~4.2x, and that is the number the headline above stands on.",
        "Long contexts stay usable: ~50–66 t/s at 65–120K prompt tokens. The drop is gradual, so a long session never stalls.",
        "Everything runs on the PFC's Arc Pro B70 (Ryzen 7 5700X); the reference recipe was measured on an equivalent XPS 8940 build — same config class, same numbers.",
      ],
    },
    library: {
      title: "The local model library",
      sub: "The B70 runs 12 local models on two engines. Four matter day-to-day; the full list is in the appendix below.",
      rows: [
        { model: "Qwen 3.8-27B", role: "the main model — daily assistant & agents", ctx: "160k", note: "vLLM XPU · 84.65 t/s" },
        { model: "Qwen3.6-35B-A3B", role: "fast workhorse (MoE — most of its 35B params stay parked)", ctx: "128k", note: "llama.cpp · ~75–78 t/s" },
        { model: "Gemma-4-12B / 26B / 31B", role: "mid-size helpers (summaries, second opinions)", ctx: "8k–128k", note: "llama.cpp · 22–93 t/s" },
        { model: "Qwen3.5-0.8B", role: "background assistant — near-instant triage", ctx: "8k", note: "llama.cpp · 202.8 t/s" },
      ],
      appendix: "Full sweep — all 12 resident models (11/12 loaded; HyperCLOVAX-SEED-Think-32B failed to load and is reported, not smoothed): Qwen3.5-0.8B Q8_0 (0.75B) · 14,262 / 202.79 · Gemma-4-E2B (4.65B) · 5,315 / 136.58 · Gemma-4-E4B (7.52B) · 3,165 / 88.48 · Gemma-4-12B-it (11.91B) · 1,512 / 49.04 · Gemma-4-26B-A4B (25.23B) · 772 / 66.89 · Qwen3.6-35B-A3B Q5_K_XL (34.66B) · 725 / 75.63 · Qwen3.6-35B-A3B Q5_K_S (35.51B) · 725 / 72.77 · Qwen3.6-35B-A3B Q4_K_M (34.66B) · 707 / 77.52 · Kanana-2-30B-A3B (30.67B) · 593 / 28.18 · Muse-Glimmer-30B (27.85B) · 569 / 22.00 · Gemma-4-31B (30.70B) · 428 / 22.62 · Qwen3.8-27B Q6_K (27.32B) · 486 / 19.92. Columns: prompt t/s · gen t/s.",
    },
    native: {
      title: "The library, measured cold — llama-bench",
      run: "run-20260814-174625",
      sub: "Every resident model, 512-token prompt / 128-token generation, fully on the Arc Pro B70 (ngl 99). One row per model, best quantization. The full 12-model table is in the appendix below.",
      cols: ["model", "size", "prompt t/s", "gen t/s", "why it matters"],
      rows: [
        ["Qwen3.5-0.8B", "0.75 B", 14262.06, 202.79, "background assistant — answers before you finish typing"],
        ["Gemma-4-12B-it", "11.91 B", 1511.79, 49.04, "mid-size helper — summaries, quick analysis"],
        ["Gemma-4-26B-A4B", "25.23 B", 772.25, 66.89, "dense mid-size — strong general reasoning"],
        ["Qwen3.6-35B-A3B", "34.66 B", 724.97, 75.63, "fastest workhorse — MoE keeps ~75 t/s at this size"],
        ["Gemma-4-31B", "30.70 B", 427.72, 22.62, "dense 31B — the floor a 27B main model must beat"],
        ["Qwen3.8-27B Q6_K", "27.32 B", 485.92, 19.92, "the previous main — 19.92 t/s is the baseline vLLM beat 4.2x"],
      ],
      failed: "Honest miss: HyperCLOVAX-SEED-Think-32B failed to load (2 s, no run) — reported, no number.",
      appendix: "Full 12-model table: Qwen3.5-0.8B Q8_0 (0.75B) 14,262.06 / 202.79 · Gemma-4-E2B Q4_K_XL (4.65B) 5,315.26 / 136.58 · Gemma-4-E4B Q4_K_XL (7.52B) 3,165.46 / 88.48 · Gemma-4-12B-it Q4_K_XL (11.91B) 1,511.79 / 49.04 · Gemma-4-26B-A4B Q4_K_M (25.23B) 772.25 / 66.89 · Qwen3.6-35B-A3B Q5_K_XL (34.66B) 724.97 / 75.63 · Qwen3.6-35B-A3B Q5_K_S (35.51B) 724.90 / 72.77 · Qwen3.6-35B-A3B Q4_K_M (34.66B) 706.68 / 77.52 · Kanana-2-30B-A3B Q4_K_M (30.67B) 593.42 / 28.18 · Muse-Glimmer-30B Q5_K_XL (27.85B) 569.33 / 22.00 · Gemma-4-31B Q4_K_XL (30.70B) 427.72 / 22.62 · Qwen3.8-27B Q6_K (27.32B) 485.92 / 19.92. Columns: prompt t/s · gen t/s.",
      findings: [
        "The MoE family (Qwen3.6-35B-A3B) is the fastest big model in the library: 72–78 t/s at ~35B, because only a slice of its parameters runs per token.",
        "Small models are embarrassingly fast: the 0.8B assistant hits 202.8 t/s — that is what keeps background automation snappy.",
        "The 27B main model was the slowest usable one at 19.92 t/s — which is exactly why it was moved to the vLLM setup above (84.65 t/s).",
      ],
    },
    mtp: {
      title: "Drafting head — where it helps",
      run: "run-20260814-192836 · 27 runs",
      sub: "Multi-token prediction (MTP) = a small head that drafts a few tokens ahead so the big model only has to verify. Tested draft depths: 2, 4, 8 tokens per step. Green = fastest for that model; red = slower than doing nothing.",
      cols: ["model", "best setting", "baseline t/s", "best t/s", "speedup", "accept %"],
      rows: [
        ["Qwen3.8-27B", "n2 (2-token draft)", 19.87, 33.20, "1.67x", "70.70"],
        ["Gemma-4-31B", "n2", 22.10, 33.06, "1.50x", "81.44"],
        ["Gemma-4-12B-it", "n2", 47.86, 71.56, "1.49x", "76.35"],
        ["Gemma-4-26B-A4B", "n4", 75.32, 93.33, "1.24x", "63.61"],
        ["Qwen3.6-35B-A3B", "(baseline — no drafting)", 77.15, 77.15, "1.00x", "—"],
      ],
      appendix: "All 27 runs (prompt t/s / decode t/s / accept % / decode vs baseline): Qwen3.8-27B Q6_K — baseline 172.01/19.87/—/1.000x, n2 148.35/33.20/70.70%/1.671x, n4 148.78/30.76/51.04%/1.548x, n8 147.42/8.83/32.91%/0.444x · Qwen3.6-35B-A3B Q5_K_S (MTP build) — baseline 270.75/77.15, n2 264.18/65.31/81.00%/0.847x, n4 267.51/65.38/62.16%/0.847x, n8 260.94/37.10/40.57%/0.481x · Qwen3.6-35B-A3B Q5_K_XL 269.58/75.87 baseline · Qwen3.6-35B-A3B Q4_K_M 273.91/78.71 baseline · Gemma-4-12B-it — baseline 458.61/47.86, n2 413.08/71.56/76.35%/1.495x, n4 413.38/67.98/62.21%/1.420x, n8 411.71/26.99/45.22%/0.564x · Gemma-4-26B-A4B — baseline 518.14/75.32, n2 516.26/85.35/73.96%/1.133x, n4 500.45/93.33/63.61%/1.239x, n8 498.94/47.25/42.68%/0.627x · Gemma-4-31B — baseline 183.47/22.10, n2 163.86/33.06/81.44%/1.496x, n4 163.66/31.22/66.69%/1.413x, n8 163.72/11.49/47.37%/0.520x · Gemma-4-E2B 1745.75/130.41 baseline · Gemma-4-E4B 973.74/85.03 baseline · Muse-Glimmer-30B 98.77/22.25 baseline · Qwen3.5-0.8B 3256.23/191.47 baseline · Kanana-2-30B-A3B 163.08/28.15 baseline.",
      findings: [
        "Short drafts win: 2-token drafts were the best setting for every model that improved — 1.49–1.67x, with the main model at 1.67x (19.87 → 33.20 t/s).",
        "Best acceptance: Gemma-4-31B at 81.44% of drafted tokens — the head was usually right, which is why it still sped things up.",
        "Honest negative: the Qwen3.6-35B-A3B MTP build ran slower than doing nothing (0.85x at n2) — its native decode is already so fast there is nothing left to draft. Baseline kept for that family.",
        "Deep drafts backfire: 8-token drafts slowed every model down (0.44–0.63x) — the drafts outran what the big model could verify.",
      ],
    },
    draft: {
      title: "Production tuning — final settings",
      run: "qwen38-prod-bench · llama-mtp-bench",
      sub: "The main model tuned at 192k context for the two real output targets (1,024 and 4,096-token answers). Best settings per target are what the production pipeline uses.",
      cols: ["profile", "answer size", "prompt t/s", "gen t/s", "accept %", "what it is for"],
      rows: [
        ["n2 p0.15", "1024", 136.88, 30.93, "70.8", "best clean decode — 1.55x over native"],
        ["n2 p0.25", "1024", 137.58, 30.93, "66.3", "same speed, lower draft temperature"],
        ["n3 p0.70", "4096", 136.94, 29.01, "83.2", "long answers — 83% accept, speed flat"],
      ],
      appendix: "All tuned profiles (Qwen3.8-27B at 192k ctx, OSL 1024/4096): n2 p0.00/1024 — 136.76/30.16/61.8% · n2 p0.15/1024 — 136.88/30.93/70.8% · n2 p0.25/1024 — 137.58/30.93/66.3% · n2 p0.35/4096 — 138.72/30.83/71.2% · n2 p0.50/1024 — 137.71/29.53/76.0% · n3 p0.70/1024 — 133.91/28.90/84.0% · n3 p0.70/4096 — 136.94/29.01/83.2% · Qwen3.6-35B-A3B baseline/1024 — 272.32/77.25/— · Qwen3.6-35B-A3B n2/1024 — 263.26/65.29/81.0% · Qwen3.6-35B-A3B n4/1024 — 264.52/65.43/62.2% · Qwen3.6-35B-A3B n8/1024 — 261.14/37.10/40.6%.",
      findings: [
        "The tuning headline: 19.92 → 30.93 t/s on the old engine (1.55x), and the same draft head inside vLLM pushed short-context decode to 84.65 t/s.",
        "n3 p0.70 is the long-answer profile: the highest acceptance (83–84%) with speed holding flat from 1,024 to 4,096-token outputs.",
        "Not universal: Qwen3.6-35B's MoE baseline (77.25 t/s) beat every draft profile — drafting is a 27B win, and the 35B runs its baseline. That is the decision made from data, not habit.",
        "Regression on record: one late n3 p0.70/4096 run dropped to 19.63 t/s — flagged and left in the raw data, not smoothed away.",
      ],
    },
  },

/* ---- Experience timeline ---- */
  experience: [
    { role: "Lab Assistant", org: "University Enterprises Inc. / Sacramento State", span: "May 2026 – Present", kind: "work",
      body: "CEC appliance energy-efficiency audits, portable-spa testing, and residential fan airflow/CFM testing (HVI 916). Controlled test environments, instrumentation, data collection, repeatability, and technical documentation." },
    { role: "Chief Design Officer", org: "Metuned LLC", span: "Jul 2023 – Jan 2026", kind: "work",
      body: "Co-founded a racecar electronics startup for affordable data-acquisition/performance solutions. Prototype planning, testing, mechanical/electrical design direction, product documentation, low-cost manufacturability." },
    { role: "Makerspace Technical Assistant", org: "Sierra College", span: "Apr 2023 – Dec 2023", kind: "work",
      body: "Trained users on 3D printers, CNC routers, laser cutters, and shop equipment; maintained, organized, and troubleshot makerspace equipment while enforcing safety standards." },
    { role: "Inventory / Packaging / Deburr Technician", org: "Vanquish Products / ASB Products", span: "Jul 2021 – Sep 2023", kind: "work",
      body: "Managed inventory flow for production parts, coordinated anodizing/laser-etch processing, and supported shipping, packaging, deburr, and quality during high-demand periods." },
    { role: "President / VP / Treasurer", org: "Sierra College Motorsports Club", span: "May 2023 – Dec 2024", kind: "lead",
      body: "Led race-prep for a 24 Hours of Lemons Mini Cooper build; coordinated student tasks, managed sponsorship/outreach, and improved team funding through events and industry partnerships." },
  ],

  education: [
    { school: "California State University, Sacramento", deg: "B.S. Mechanical Engineering", span: "Dec 2024 – Present · exp. Fall 2026", gpa: "3.358" },
    { school: "Sierra College", deg: "A.S. Natural Science + A.S.-T Engineering", span: "Jul 2019 – Dec 2024", gpa: "2.73 · 30–40 hrs/wk", cert: "SOLIDWORKS Foundations" },
  ],

  skills: [
    { g: "Controls & Automation", items: "ABB/Rexroth robotics, motion control, sensors, low-voltage troubleshooting, commissioning, fault isolation, root-cause analysis" },
    { g: "Digital Mfg / OT", items: "PLC/HMI/SCADA fundamentals, industrial controls, OT/networking, Tailscale, Linux, local-AI workflow automation, human-reviewed agents" },
    { g: "CAD/CAM & Fab", items: "Fusion 360, SolidWorks, AutoCAD, CNC routing, Haas CNC, milling, lathe, laser cutting, deburr, rapid prototyping, 3D printing" },
    { g: "Programming & Data", items: "Python, C, Java, MATLAB, Klipper, llama.cpp, Qwen/Gemma local models, test data collection, engineering documentation" },
    { g: "Communication", items: "technical training, operator/user support, vendor coordination, shop safety, procedure writing, project planning, sponsorship/outreach" },
  ],
});
